---
load_datasets: True # load raw or processed datasets instead of task-specific splits
reprocess_datasets: False # hate/non-hate ratio to sample each dataset
hate_ratio: 0.3
classifier:
  name: 'bert'
  settings:
    n_gpus: 1
    gpu_ids: [0] # list of ids or 'all'

heg_comparison:
  run: False
  create_splits: False # create comparison splits
  cv_runs: 5

pca:
  run: True
  create_identity_datasets: ['separate', 'combined'] # False or list of either or both 'separate', 'combined'
  combine_datasets: True
  incremental: False

datasets:
  elsherief2021:
    - implicit_hate_v1_stg3_posts.tsv        
    - implicit_hate_v1_stg1_posts.tsv
  kennedy2020:
    - ucberkeley-dlab/measuring-hate-speech
    - binary
  salminen2018: []
  sbic:
    - SBIC.v2.agg.trn.csv
    - SBIC.v2.agg.dev.csv
    - SBIC.v2.agg.tst.csv
  cad:
    - cad_v1_1.tsv
  hatexplain:
    - Data/dataset.json
  civilcomments:
    - all_data.csv
